# config/config.yaml

artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_kaggle_dataset_id: "paultimothymooney/chest-xray-pneumonia"
  unzip_dir: artifacts/data_ingestion/
  # We will create these three files now
  train_df_path: artifacts/data_ingestion/train_df.csv
  test_df_path: artifacts/data_ingestion/test_df.csv
  val_df_path: artifacts/data_ingestion/val_df.csv

data_transformation:
  root_dir: artifacts/data_transformation
  # We now have three sources
  train_data_path: artifacts/data_ingestion/train_df.csv
  test_data_path: artifacts/data_ingestion/test_df.csv
  val_data_path: artifacts/data_ingestion/val_df.csv
  # And will create three outputs
  train_dataset_path: artifacts/data_transformation/train_dataset
  test_dataset_path: artifacts/data_transformation/test_dataset
  val_dataset_path: artifacts/data_transformation/val_dataset

model_training:
  root_dir: artifacts/model_training
  trained_model_path: artifacts/model_training/model
  model_name: "google/vit-base-patch16-224-in21k"
  # We'll use the validation set for evaluation during training
  train_dataset_path: artifacts/data_transformation/train_dataset
  val_dataset_path: artifacts/data_transformation/val_dataset

model_evaluation:
  root_dir: artifacts/model_evaluation
  model_path: artifacts/model_training/model
  # Final evaluation is done on the unseen test set
  test_dataset_path: artifacts/data_transformation/test_dataset
  metrics_file_name: artifacts/model_evaluation/metrics.json
  mlflow_uri: "https://dagshub.com/AlyyanAhmed21/Chest-X-ray-Pneumonia-Detection-with-ViT.mlflow"