# .github/workflows/main.yml (Final, Git LFS Version)

name: Deploy App to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy-to-hub:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out your repo. `lfs: true` is crucial.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true # This automatically pulls your Git LFS files (the model)

      # Step 2: Log in to Hugging Face Hub
      - name: Log in to Hugging Face Hub
        uses: huggingface-hub/login@v1
        with:
          token: ${{ secrets.HF_TOKEN }}

      # Step 3: Push the complete app to the Space
      - name: Push to HF Space
        env:
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_SPACE_NAME: ${{ secrets.HF_SPACE_NAME }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          # Clone the Space repo into a new directory
          git clone https://huggingface.co/spaces/${HF_USERNAME}/${HF_SPACE_NAME} hf_space_repo
          # Copy all necessary files into the Space repo
          rsync -av --delete app/ app.py requirements.txt README.md artifacts/model_training/model/ hf_space_repo/
          cd hf_space_repo
          git add .
          git commit -m "Automatic deployment from GitHub Action" || echo "No changes to commit"
          # Force push is safer here to ensure the Space exactly matches the repo
          git push --force 
