# .github/workflows/main.yml

name: Deploy App to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy-to-hub:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Push to HF Space
        env:
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_SPACE_NAME: ${{ secrets.HF_SPACE_NAME }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Configure git identity
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

          # Clone the Hugging Face Space using token auth
          git clone https://user:$HF_TOKEN@huggingface.co/spaces/${HF_USERNAME}/${HF_SPACE_NAME} hf_space_repo

          # Sync files, excluding .git and workflows
          rsync -av app/ app.py requirements.txt README.md artifacts/model_training/model/ hf_space_repo/

          cd hf_space_repo
          git add .
          git commit -m "Automatic deployment from GitHub Action" || echo "No changes to commit"

          # Push using token auth
          git push https://user:$HF_TOKEN@huggingface.co/spaces/${HF_USERNAME}/${HF_SPACE_NAME}.git
