# .github/workflows/main.yml (Final Version with Git Config)

name: Deploy App to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy-to-hub:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Log in to Hugging Face Hub and configure Git
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install huggingface_hub
          huggingface-cli login --token $HF_TOKEN --add-to-git-credential

      - name: Push to HF Space
        env:
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_SPACE_NAME: ${{ secrets.HF_SPACE_NAME }}
        run: |
          # --- THIS IS THE FIX ---
          # Set a dummy user identity for the git commit
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          
          # Now the rest of the script will work
          git clone https://huggingface.co/spaces/${HF_USERNAME}/${HF_SPACE_NAME} hf_space_repo
          
          rsync -av --delete --exclude='.git/' --exclude='.github/' ./ hf_space_repo/
          
          cd hf_space_repo
          git add .
          git commit -m "Automatic deployment from GitHub Action" || echo "No changes to commit"
          git push
